version: "3.9"

services:
  traefik:
    image: traefik:latest
    command: >
      --providers.docker
      --providers.docker.network=gateway
      --providers.docker.exposedByDefault=false
      --api.dashboard=true
      --entryPoints.web.address=:80
      --entryPoints.websecure.address=:443
      --log.level=INFO
      --certificatesresolvers.step.acme.caserver=https://step.local:9000/acme/traefik/directory
      --certificatesresolvers.step.acme.tlschallenge=true
      --certificatesresolvers.step.acme.email=root@localhost
      --certificatesresolvers.step.acme.keytype=RSA4096
      --certificatesresolvers.step.acme.storage=acme.json
    environment:
      - TZ=UTC
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json
    restart: unless-stopped
    depends_on:
      step:
        condition: service_healthy
    logging:
      options:
        max-size: "8m"
        max-file: "10"
    networks:
      external:
        aliases:
          - traefik.local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=step"
      - "traefik.http.middlewares.redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect.redirectscheme.permanent=false"

  step:
    image: smallstep/step-ca:latest
    restart: unless-stopped
    logging:
      options:
        max-size: "8m"
        max-file: "10"
    environment:
      - TZ=UTC
      - DOCKER_STEPCA_INIT_NAME=OpenProject Development
      - DOCKER_STEPCA_INIT_DNS_NAMES=step.local,step,localhost
      - DOCKER_STEPCA_INIT_PROVISIONER_NAME=openproject
      - DOCKER_STEPCA_INIT_PASSWORD=openproject
    volumes:
      - step:/home/step
    networks:
      external:
        aliases:
          - step.local

volumes:
  step:

networks:
  external:
    name: gateway
    external: true
