services:
  backend:
    # The backend container needs some variables to be configured properly
    environment:
      OPENPROJECT_CLI_PROXY: 'https://${OPENPROJECT_DEV_HOST}'
      OPENPROJECT_DEV_EXTRA_HOSTS: '${OPENPROJECT_DEV_HOST}'
      OPENPROJECT_HTTPS: true
    networks:
      - external

  frontend:
    # The command for the frontend needs to be overwritten
    command: 'node --max_old_space_size=8096 ./node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --public-host https://${OPENPROJECT_DEV_HOST}'
    networks:
      - external
    # Those label interpreted by traefik to create the correct HTTP router
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.openproject.rule=Host(`${OPENPROJECT_DEV_HOST}`)"
      - "traefik.http.routers.openproject.entrypoints=websecure"
      - "traefik.http.routers.openproject.tls=true"
      - "traefik.http.routers.openproject.tls.certresolver=step"

# You need to define the same external network
# that is defined in the TLS proxy compose file
networks:
  external:
    name: gateway
    external: true
