Lint/RedundantCopDisableDirective:
  Exclude:
    - 'app/contracts/members/base_contract.rb'
    - 'app/controllers/admin/settings/new_project_settings_controller.rb'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/oauth_clients_controller.rb'
    - 'app/controllers/work_packages/moves_controller.rb'
    - 'app/helpers/accounts_helper.rb'
    - 'app/helpers/flash_messages_helper.rb'
    - 'app/helpers/pagination_helper.rb'
    - 'app/models/colors/hex_color.rb'
    - 'app/models/journable/historic_active_record_relation.rb'
    - 'app/models/notification_settings/scopes/applicable.rb'
    - 'app/models/projects/scopes/allowed_to.rb'
    - 'app/models/setting/mail_settings.rb'
    - 'app/models/users/permission_checks.rb'
    - 'app/models/work_packages/scopes/allowed_to.rb'
    - 'app/models/work_packages/scopes/relatable.rb'
    - 'app/seeders/development_data/shared_work_packages_seeder.rb'
    - 'app/seeders/env_data/ldap_seeder.rb'
    - 'app/services/api/v3/parse_query_params_service.rb'
    - 'app/services/authorization/user_permissible_service.rb'
    - 'app/services/oauth_clients/connection_manager.rb'
    - 'app/services/update_query_from_params_service.rb'
    - 'app/services/users/set_attributes_service.rb'
    - 'app/services/work_packages/set_attributes_service.rb'
    - 'app/services/work_packages/set_schedule_service.rb'
    - 'app/workers/copy_project_job.rb'
    - 'config/initializers/mail_starttls_patch.rb'
    - 'db/migrate/20221213092910_remove_default_values_from_journal_tables_definition.rb'
    - 'db/migrate/tables/custom_fields.rb'
    - 'db/migrate/tables/messages.rb'
    - 'db/migrate/tables/projects.rb'
    - 'db/migrate/tables/time_entries.rb'
    - 'db/migrate/tables/users.rb'
    - 'db/migrate/tables/work_package_journals.rb'
    - 'db/migrate/tables/work_packages.rb'
    - 'lib_static/rubocop/cop/open_project/use_service_result_factory_methods.rb'
    - 'lib/open_project/ui/extensible_tabs.rb'
    - 'lib/redmine/menu_manager/menu_helper.rb'
    - 'modules/backlogs/lib/open_project/backlogs/patches/api/work_package_schema_representer.rb'
    - 'modules/costs/app/models/cost_scopes.rb'
    - 'modules/github_integration/db/migrate/20210407110000_github_integration_models.rb'
    - 'modules/github_integration/lib/open_project/github_integration/services/upsert_pull_request.rb'
    - 'modules/gitlab_integration/db/migrate/20211015110000_gitlab_integration_models.rb'
    - 'modules/gitlab_integration/lib/open_project/gitlab_integration/patches/api/work_package_representer.rb'
    - 'modules/gitlab_integration/lib/open_project/gitlab_integration/services/upsert_issue.rb'
    - 'modules/gitlab_integration/lib/open_project/gitlab_integration/services/upsert_issue_note.rb'
    - 'modules/gitlab_integration/lib/open_project/gitlab_integration/services/upsert_merge_request.rb'
    - 'modules/ldap_groups/app/models/ldap_groups/synchronized_group.rb'
    - 'modules/meeting/app/services/meetings/ical_service.rb'
    - 'modules/reporting/app/controllers/cost_reports_controller.rb'
    - 'modules/reporting/app/models/cost_query/filter/logged_by_id.rb'
    - 'modules/reporting/app/workers/cost_query/export_job.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/oauth_client_credentials.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/authentication_strategies/oauth_user_token.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/add_user_to_group_command.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/create_folder_command.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/file_info_query.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/files_info_query.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/files_query.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/group_users_query.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/internal/propfind_query.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/internal/propfind_query_legacy.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/remove_user_from_group_command.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/nextcloud/set_permissions_command.rb'
    - 'modules/storages/app/common/storages/peripherals/storage_interaction/one_drive/util.rb'
    - 'modules/storages/app/controllers/storages/admin/project_storages_controller.rb'
    - 'modules/storages/app/controllers/storages/project_storages_controller.rb'
    - 'modules/storages/app/services/projects/copy/storages_dependent_service.rb'
    - 'modules/storages/app/services/storages/file_links/copy_file_links_service.rb'
    - 'modules/storages/app/services/storages/nextcloud_group_folder_properties_sync_service.rb'
    - 'modules/storages/app/services/storages/one_drive_managed_folder_sync_service.rb'
    - 'modules/storages/app/validator/nextcloud_application_credentials_validator.rb'
    - 'modules/two_factor_authentication/app/controllers/two_factor_authentication/base_controller.rb'
    - 'modules/two_factor_authentication/app/controllers/two_factor_authentication/forced_registration/two_factor_devices_controller.rb'
    - 'modules/two_factor_authentication/app/controllers/two_factor_authentication/my/two_factor_devices_controller.rb'
    - 'modules/two_factor_authentication/lib/open_project/two_factor_authentication/token_strategy/sns.rb'
    - 'script/bulk_run_rspec'
    - 'spec/requests/api/v3/work_packages/update_resource_spec.rb'
    - 'spec/requests/oauth_clients/callback_flow_spec.rb'
    - 'spec/support/browsers/chrome.rb'
    - 'spec/support/mocked_permission_helper.rb'
    - 'spec/workers/work_packages/exports/export_job_spec.rb'
