deployments:
  openproject:
    filename:
      ./docker-compose.pullpreview.yml
    install:
      - docker-compose -f docker-compose.pullpreview.yml up -d
      - sleep 10s 
    pre_launch:
      - target: openproject
        command:
        options: