language: ruby
rvm:
  - 1.9.3
env:
  - "RAILS_ENV=test DB=mysql2 BUNDLE_WITHOUT=rmagick:mysql:postgres:sqlite"
  - "RAILS_ENV=test DB=postgres BUNDLE_WITHOUT=rmagick:mysql:mysql2:sqlite"
  - "RAILS_ENV=test DB=sqlite BUNDLE_WITHOUT=rmagick:mysql:mysql2:postgres"
script: "bundle exec rake"
before_install:
  - "sudo apt-get update -qq"
  - "sudo apt-get --no-install-recommends install git subversion"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - "RAILS_ENV=production bundle exec rake ci:travis:prepare"
branches:
  only:
    - feature/rails3
notifications:
  email: false
