version: "3.7"

networks:
  testing:

services:
  ci:
    build:
      context: ./docker/ci/
      dockerfile: Dockerfile
    environment:
      RSPEC_RETRY_RETRY_COUNT: "${CI_RETRY_COUNT:-3}"
      JOBS: "${CI_JOBS:-8}"
      OPENPROJECT_ENABLE_CAPYBARA_SCREENSHOT_S3_UPLOADS: "${OPENPROJECT_ENABLE_CAPYBARA_SCREENSHOT_S3_UPLOADS:-true}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_ACCESS_KEY_SECRET: "${AWS_SECRET_ACCESS_KEY}"
    tmpfs:
      - "/tmp"
    volumes:
      - ".:/home/dev/openproject"
      - "${CI_CACHE_PATH:-/tmp}/op-bundle:/usr/local/bundle"
      - "${CI_CACHE_PATH:-/tmp}/op-node:/home/dev/openproject/frontend/node_modules"
    networks:
      - testing
