version: '3.7'

volumes:
  caddy_data:

services:
  file-server:
    build:
      context: .
      target: prod
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - "caddy_data:/data"
