version: '3.7'

volumes:
  caddy_data:

services:
  file-server:
    build:
      context: .
      target: prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data"
