version: '3.7'

volumes:
  caddy_data:

services:
  file-server:
    build:
      context: .
      target: prod
    restart: unless-stopped
    command: "caddy file-server -root /srv/storybook -domain '${PULLPREVIEW_URL}' -listen 0.0.0.0:8080"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data"
