name: opencode-sync
on:
  workflow_dispatch:
  schedule:
    - cron: '5 */1 * * *' # Every hour

permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  to_gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@gitlab.opencode.de:bmi/souveraener_arbeitsplatz/component-code/management/openproject/openproject-core.git
          ssh_private_key:
            ${{ secrets.OPENCODE_SYNC_SSH_PRIVATE_KEY }}
